#!/usr/bin/env python3
"""data.js を生成するビルドスクリプト。

セリフ本文は scenes_manual.py の MANUAL 辞書に手書きされたものを使う
（テンプレート生成はしない。一文一文に固有の情景を持たせるため）。
このファイルは絵文字ごとのカテゴリ情報とアイコン・レイアウトの組み立てだけを担当する。
実行: python3 build_data.py
"""
import json
import random

from scenes_manual import MANUAL

# ---------------------------------------------------------------
# 絵文字一覧: (コードポイント, 韓国語, 日本語, カテゴリ, テンプレ番号固定=None)
# カテゴリ: food drink animal object vehicle nature sport music place person special
# ---------------------------------------------------------------
E = [
    ("1f308", "무지개", "虹", "nature", None),
    ("1f309", "야경", "夜景", "place", 1),
    ("1f30a", "파도", "波", "nature", None),
    ("1f30d", "지구", "地球", "special", None),
    ("1f319", "달", "月", "nature", None),
    ("1f32a", "토네이도", "竜巻", "special", None),
    ("1f32d", "핫도그", "ホットドッグ", "food", None),
    ("1f32e", "타코", "タコス", "food", None),
    ("1f330", "밤", "栗", "food", None),
    ("1f333", "나무", "木", "nature", None),
    ("1f337", "튤립", "チューリップ", "nature", None),
    ("1f338", "벚꽃", "桜", "nature", 1),
    ("1f33b", "해바라기", "ひまわり", "nature", None),
    ("1f33d", "옥수수", "とうもろこし", "food", None),
    ("1f33e", "벼 이삭", "稲穂", "nature", None),
    ("1f343", "낙엽", "落ち葉", "nature", None),
    ("1f344", "버섯", "きのこ", "food", None),
    ("1f345", "토마토", "トマト", "food", None),
    ("1f346", "가지", "なす", "food", None),
    ("1f347", "포도", "ぶどう", "food", None),
    ("1f348", "멜론", "メロン", "food", None),
    ("1f349", "수박", "スイカ", "food", None),
    ("1f34a", "귤", "みかん", "food", None),
    ("1f34b", "레몬", "レモン", "food", None),
    ("1f34c", "바나나", "バナナ", "food", None),
    ("1f34d", "파인애플", "パイナップル", "food", None),
    ("1f34e", "사과", "りんご", "food", None),
    ("1f350", "배", "梨", "food", None),
    ("1f351", "복숭아", "桃", "food", None),
    ("1f352", "체리", "さくらんぼ", "food", None),
    ("1f353", "딸기", "いちご", "food", None),
    ("1f354", "햄버거", "ハンバーガー", "food", None),
    ("1f355", "피자", "ピザ", "food", None),
    ("1f357", "치킨", "チキン", "food", None),
    ("1f358", "센베이", "せんべい", "food", None),
    ("1f359", "주먹밥", "おにぎり", "food", None),
    ("1f35a", "밥", "ごはん", "food", None),
    ("1f35b", "카레", "カレー", "food", None),
    ("1f35c", "라면", "ラーメン", "food", None),
    ("1f35d", "스파게티", "スパゲッティ", "food", None),
    ("1f35e", "빵", "パン", "food", None),
    ("1f35f", "감자튀김", "フライドポテト", "food", None),
    ("1f360", "고구마", "焼き芋", "food", None),
    ("1f361", "경단", "だんご", "food", None),
    ("1f363", "초밥", "お寿司", "food", None),
    ("1f364", "새우튀김", "エビフライ", "food", None),
    ("1f366", "아이스크림", "ソフトクリーム", "food", None),
    ("1f369", "도넛", "ドーナツ", "food", None),
    ("1f36a", "쿠키", "クッキー", "food", None),
    ("1f36b", "초콜릿", "チョコレート", "food", None),
    ("1f36c", "사탕", "キャンディ", "food", None),
    ("1f36e", "푸딩", "プリン", "food", None),
    ("1f36f", "꿀", "はちみつ", "special", None),
    ("1f370", "케이크", "ケーキ", "food", None),
    ("1f371", "도시락", "お弁当", "food", None),
    ("1f372", "찌개", "チゲ鍋", "food", None),
    ("1f375", "녹차", "お茶", "drink", None),
    ("1f37f", "팝콘", "ポップコーン", "food", None),
    ("1f380", "리본", "リボン", "object", None),
    ("1f381", "선물", "プレゼント", "special", None),
    ("1f384", "트리", "クリスマスツリー", "special", None),
    ("1f385", "산타", "サンタ", "special", None),
    ("1f388", "풍선", "風船", "object", None),
    ("1f38f", "잉어 깃발", "こいのぼり", "object", 0),
    ("1f392", "책가방", "リュック", "object", None),
    ("1f3a4", "마이크", "マイク", "special", None),
    ("1f3a7", "헤드폰", "ヘッドホン", "special", None),
    ("1f3a8", "팔레트", "絵の具", "special", None),
    ("1f3ae", "게임", "ゲーム", "sport", None),
    ("1f3af", "다트", "ダーツ", "sport", None),
    ("1f3b3", "볼링", "ボウリング", "sport", None),
    ("1f3b7", "색소폰", "サックス", "music", None),
    ("1f3b8", "기타", "ギター", "music", None),
    ("1f3b9", "피아노", "ピアノ", "music", None),
    ("1f3ba", "트럼펫", "トランペット", "music", None),
    ("1f3bb", "바이올린", "バイオリン", "music", None),
    ("1f3be", "테니스", "テニス", "sport", None),
    ("1f3c0", "농구", "バスケ", "sport", None),
    ("1f3c5", "메달", "メダル", "special", None),
    ("1f3c6", "트로피", "トロフィー", "special", None),
    ("1f3c9", "럭비", "ラグビー", "sport", None),
    ("1f3cd", "오토바이", "バイク", "vehicle", None),
    ("1f3d0", "배구", "バレーボール", "sport", None),
    ("1f3e0", "집", "家", "special", None),
    ("1f3f0", "성", "お城", "place", 0),
    ("1f3f8", "배드민턴", "バドミントン", "sport", None),
    ("1f406", "표범", "ヒョウ", "animal", None),
    ("1f40a", "악어", "ワニ", "animal", None),
    ("1f40c", "달팽이", "カタツムリ", "animal", None),
    ("1f40d", "뱀", "ヘビ", "animal", None),
    ("1f411", "양", "羊", "animal", None),
    ("1f414", "닭", "ニワトリ", "animal", None),
    ("1f418", "코끼리", "ゾウ", "animal", None),
    ("1f419", "문어", "タコ", "animal", None),
    ("1f41c", "개미", "アリ", "animal", None),
    ("1f41d", "꿀벌", "ミツバチ", "animal", None),
    ("1f41e", "무당벌레", "てんとう虫", "animal", None),
    ("1f41f", "물고기", "魚", "animal", None),
    ("1f422", "거북이", "カメ", "animal", None),
    ("1f424", "병아리", "ひよこ", "animal", None),
    ("1f426", "새", "鳥", "animal", None),
    ("1f427", "펭귄", "ペンギン", "animal", None),
    ("1f428", "코알라", "コアラ", "animal", None),
    ("1f42b", "낙타", "ラクダ", "animal", None),
    ("1f42c", "돌고래", "イルカ", "animal", 0),
    ("1f42d", "생쥐", "ネズミ", "animal", None),
    ("1f42e", "소", "牛", "animal", None),
    ("1f42f", "호랑이", "トラ", "animal", None),
    ("1f430", "토끼", "ウサギ", "animal", None),
    ("1f431", "고양이", "ネコ", "animal", None),
    ("1f433", "고래", "クジラ", "animal", 0),
    ("1f435", "원숭이", "サル", "animal", None),
    ("1f436", "강아지", "犬", "animal", None),
    ("1f437", "돼지", "ブタ", "animal", None),
    ("1f438", "개구리", "カエル", "animal", None),
    ("1f439", "햄스터", "ハムスター", "animal", None),
    ("1f43a", "늑대", "オオカミ", "animal", None),
    ("1f43b", "곰", "クマ", "animal", None),
    ("1f43c", "판다", "パンダ", "animal", 0),
    ("1f43f", "다람쥐", "リス", "animal", None),
    ("1f441", "눈", "目", "special", None),
    ("1f442", "귀", "耳", "special", None),
    ("1f444", "입", "口", "special", None),
    ("1f451", "왕관", "王冠", "object", None),
    ("1f453", "안경", "メガネ", "object", None),
    ("1f454", "넥타이", "ネクタイ", "object", None),
    ("1f455", "티셔츠", "Tシャツ", "object", None),
    ("1f456", "청바지", "ジーンズ", "object", None),
    ("1f457", "원피스", "ワンピース", "object", 3),
    ("1f45c", "핸드백", "ハンドバッグ", "object", None),
    ("1f45f", "운동화", "スニーカー", "object", None),
    ("1f461", "샌들", "サンダル", "object", None),
    ("1f462", "부츠", "ブーツ", "object", None),
    ("1f466", "소년", "男の子", "special", None),
    ("1f467", "소녀", "女の子", "special", None),
    ("1f474", "할아버지", "おじいちゃん", "special", None),
    ("1f475", "할머니", "おばあちゃん", "special", None),
    ("1f476", "아기", "赤ちゃん", "special", None),
    ("1f48a", "약", "薬", "special", None),
    ("1f48d", "반지", "指輪", "special", None),
    ("1f48e", "보석", "宝石", "object", None),
    ("1f4a1", "전구", "電球", "special", None),
    ("1f4a7", "물방울", "しずく", "special", None),
    ("1f4b0", "돈", "お金", "object", 0),
    ("1f4bb", "노트북", "ノートパソコン", "object", None),
    ("1f4c5", "달력", "カレンダー", "special", None),
    ("1f4cf", "자", "定規", "object", None),
    ("1f4d6", "책", "本", "object", None),
    ("1f4f0", "신문", "新聞", "object", None),
    ("1f4f1", "휴대폰", "スマホ", "object", 4),
    ("1f4f7", "카메라", "カメラ", "special", None),
    ("1f4fa", "텔레비전", "テレビ", "special", None),
    ("1f4fb", "라디오", "ラジオ", "special", None),
    ("1f50b", "배터리", "バッテリー", "special", None),
    ("1f511", "열쇠", "鍵", "object", 2),
    ("1f514", "종", "鐘", "special", None),
    ("1f525", "불꽃", "炎", "special", None),
    ("1f54a", "비둘기", "ハト", "animal", None),
    ("1f56f", "촛불", "ろうそく", "special", None),
    ("1f576", "선글라스", "サングラス", "object", None),
    ("1f577", "거미", "クモ", "animal", None),
    ("1f58d", "크레용", "クレヨン", "object", None),
    ("1f5a8", "프린터", "プリンター", "object", None),
    ("1f5fa", "지도", "地図", "object", None),
    ("1f5fb", "후지산", "富士山", "place", 0),
    ("1f680", "로켓", "ロケット", "vehicle", 0),
    ("1f681", "헬리콥터", "ヘリコプター", "vehicle", None),
    ("1f683", "기차", "電車", "vehicle", None),
    ("1f68c", "버스", "バス", "vehicle", None),
    ("1f691", "구급차", "救急車", "vehicle", 1),
    ("1f692", "소방차", "消防車", "vehicle", 1),
    ("1f693", "경찰차", "パトカー", "vehicle", 1),
    ("1f695", "택시", "タクシー", "vehicle", None),
    ("1f697", "자동차", "車", "vehicle", None),
    ("1f69a", "트럭", "トラック", "vehicle", 1),
    ("1f69d", "모노레일", "モノレール", "vehicle", None),
    ("1f6a0", "케이블카", "ロープウェイ", "vehicle", None),
    ("1f6a2", "배", "船", "vehicle", 0),
    ("1f6a9", "깃발", "旗", "object", None),
    ("1f6b2", "자전거", "自転車", "vehicle", None),
    ("1f6f5", "스쿠터", "スクーター", "vehicle", None),
    ("1f6f6", "카누", "カヌー", "vehicle", 2),
    ("1f6f8", "UFO", "UFO", "special", None),
    ("1f6f9", "킥보드", "キックボード", "vehicle", None),
    ("1f916", "로봇", "ロボット", "special", None),
    ("1f941", "드럼", "ドラム", "music", None),
    ("1f94a", "권투", "ボクシング", "sport", None),
    ("1f951", "아보카도", "アボカド", "food", None),
    ("1f952", "오이", "きゅうり", "food", None),
    ("1f953", "베이컨", "ベーコン", "food", None),
    ("1f954", "감자", "じゃがいも", "food", None),
    ("1f955", "당근", "にんじん", "food", None),
    ("1f957", "샐러드", "サラダ", "food", None),
    ("1f95a", "달걀", "卵", "food", None),
    ("1f95b", "우유", "牛乳", "drink", None),
    ("1f95c", "땅콩", "ピーナッツ", "food", None),
    ("1f95d", "키위", "キウイ", "food", None),
    ("1f95e", "팬케이크", "パンケーキ", "food", None),
    ("1f965", "코코넛", "ココナッツ", "food", None),
    ("1f966", "브로콜리", "ブロッコリー", "food", None),
    ("1f968", "프레첼", "プレッツェル", "food", None),
    ("1f969", "고기", "お肉", "food", None),
    ("1f96c", "배추", "白菜", "special", None),
    ("1f96d", "망고", "マンゴー", "food", None),
    ("1f980", "게", "カニ", "animal", None),
    ("1f981", "사자", "ライオン", "animal", None),
    ("1f986", "오리", "カモ", "animal", None),
    ("1f987", "박쥐", "コウモリ", "animal", None),
    ("1f989", "부엉이", "フクロウ", "animal", None),
    ("1f98a", "여우", "キツネ", "animal", None),
    ("1f98b", "나비", "チョウ", "animal", None),
    ("1f98c", "사슴", "シカ", "animal", None),
    ("1f98d", "고릴라", "ゴリラ", "animal", None),
    ("1f98e", "도마뱀", "トカゲ", "animal", None),
    ("1f98f", "코뿔소", "サイ", "animal", None),
    ("1f990", "새우", "エビ", "animal", None),
    ("1f991", "오징어", "イカ", "animal", None),
    ("1f992", "기린", "キリン", "animal", None),
    ("1f993", "얼룩말", "シマウマ", "animal", None),
    ("1f994", "고슴도치", "ハリネズミ", "animal", None),
    ("1f998", "캥거루", "カンガルー", "animal", None),
    ("1f99a", "공작", "クジャク", "animal", None),
    ("1f99b", "하마", "カバ", "animal", None),
    ("1f99c", "앵무새", "オウム", "animal", None),
    ("1f99d", "너구리", "アライグマ", "animal", None),
    ("1f9a5", "나무늘보", "ナマケモノ", "animal", None),
    ("1f9a9", "홍학", "フラミンゴ", "animal", None),
    ("1f9ad", "물개", "アザラシ", "animal", 0),
    ("1f9b4", "뼈다귀", "骨", "special", None),
    ("1f9c0", "치즈", "チーズ", "food", None),
    ("1f9c2", "소금", "塩", "special", None),
    ("1f9c3", "주스", "ジュース", "drink", None),
    ("1f9c5", "양파", "玉ねぎ", "food", None),
    ("1f9c7", "와플", "ワッフル", "food", None),
    ("1f9c8", "버터", "バター", "special", None),
    ("1f9ca", "얼음", "氷", "special", None),
    ("1f9e2", "모자", "キャップ", "object", None),
    ("1f9e4", "장갑", "手袋", "object", None),
    ("1f9e5", "코트", "コート", "object", None),
    ("1f9e6", "양말", "靴下", "object", None),
    ("1f9f8", "곰 인형", "ぬいぐるみ", "object", 3),
    ("1f9f9", "빗자루", "ほうき", "special", None),
    ("1fa82", "낙하산", "パラシュート", "vehicle", 2),
    ("1fa99", "동전", "コイン", "special", None),
    ("1fa9f", "창문", "窓", "special", None),
    ("1faa8", "돌", "石", "special", None),
    ("1fad1", "파프리카", "パプリカ", "food", None),
    ("231a", "손목시계", "腕時計", "object", None),
    ("2600", "해", "太陽", "nature", None),
    ("2602", "우산", "傘", "special", None),
    ("260e", "전화", "電話", "special", None),
    ("2615", "커피", "コーヒー", "drink", 0),
    ("26a1", "번개", "雷", "special", None),
    ("26bd", "축구", "サッカー", "sport", None),
    ("26c4", "눈사람", "雪だるま", "special", None),
    ("26d1", "헬멧", "ヘルメット", "special", None),
    ("26e9", "신사", "神社", "place", 0),
    ("26f0", "산", "山", "place", 1),
    ("26f5", "요트", "ヨット", "vehicle", None),
    ("26f7", "스키", "スキー", "sport", None),
    ("26f8", "스케이트", "スケート", "sport", None),
    ("26fa", "텐트", "テント", "object", 5),
    ("2702", "가위", "はさみ", "object", None),
    ("2708", "비행기", "飛行機", "vehicle", None),
    ("2709", "편지", "手紙", "special", None),
    ("270b", "손", "手", "special", None),
    ("270f", "연필", "鉛筆", "object", None),
    ("2764", "하트", "ハート", "special", None),
    ("2b50", "별", "星", "nature", None),
]

# カテゴリごとの脇役アイコン候補
SUPPORT = {
    "food":    ["2b50", "2764", "2615", "1f370"],
    "drink":   ["1f370", "2764", "2b50", "1f36a"],
    "animal":  ["1f333", "2600", "1f343", "2764"],
    "object":  ["2b50", "1f381", "1f4a1", "2764"],
    "vehicle": ["1f5fa", "2600", "2b50", "1f3e0"],
    "nature":  ["1f4f7", "2764", "2b50", "2600"],
    "sport":   ["1f3c6", "1f3c5", "1f525", "2b50"],
    "music":   ["1f3a7", "2764", "2b50", "1f514"],
    "place":   ["1f4f7", "1f5fa", "2b50", "2600"],
    "person":  ["2764", "2b50", "1f3e0", "1f381"],
    "special": ["2b50", "2764", "1f4a1", "2600"],
}

PEOPLE = ["1f467", "1f466", "1f475", "1f474", "1f476"]
LAYOUTS = ["romance", "lineup", "farewell", "confrontation"]
ANIMS = ["bounce", "float", "shake"]


def build():
    scenes = []
    for i, (code, ko, ja, cat, fixed) in enumerate(E):
        entry = MANUAL[code]
        chunks = [(k, j) for k, j in entry["chunks"]]
        full_ja = entry["full_ja"]
        icon_cat = cat

        full_ko = " ".join(c[0] for c in chunks)

        # アイコン: 人物(2/3の頻度) + 主題 + 脇役2つ。重複は除く
        icons = []
        if i % 3 != 2:
            icons.append(PEOPLE[i % len(PEOPLE)] + ".svg")
        icons.append(code + ".svg")
        pool = [s for s in SUPPORT[icon_cat] if s != code and s + ".svg" not in icons]
        icons += [s + ".svg" for s in (pool[i % len(pool):] + pool[: i % len(pool)])[:2]]

        scenes.append({
            "id": f"emoji-{code}",
            "title": ja,
            "chunks": [{"korean": k, "japanese": j} for k, j in chunks],
            "result": {
                "full_korean": full_ko,
                "full_japanese": full_ja,
                "visuals": {
                    "icons": icons,
                    "layout": LAYOUTS[i % len(LAYOUTS)],
                    "animation": ANIMS[i % len(ANIMS)],
                },
            },
        })

    random.Random(42).shuffle(scenes)
    return scenes


HEADER = """\
// このファイルは build_data.py が生成する。直接編集せず、
// build_data.py を編集して `python3 build_data.py` で再生成すること。
window.SCENES_DATA = """

if __name__ == "__main__":
    data = {"scenes": build()}
    with open("data.js", "w", encoding="utf-8") as f:
        f.write(HEADER + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")
    print(f"data.js generated: {len(data['scenes'])} scenes")
